
FR_LAF_W:
  ELOUGA Eva-Brooklyn: MB
  FANGUEDOU Fatoumata: MB
  LOFF DA SILVA Raquel: MB
  ANDRIAMAHERIZO - RANAIVO MARIE RAPHAELLE: MB
  MILOSIC Nika: MB
  JORGENSEN AMALIE: MB
  HAGGERTY Julia: MB

FR_LAM: {}
